# action.yaml
name: "Axway APIM-CLI Github Action"
description: "Use the Axway APIM-CLI in you GitHub action workflows. Import APIs, users, organizations and applications in batch mode."
branding:
  icon: 'award'
  color: 'red'

inputs:
  command:
    description: "Run an APIM-CLI command. For example: 'apim api check-certs'. You may combine this with apimExtraArgs depending on you the command you use."
    required: ture

runs:
  using: "docker"
  image: "Dockerfile"
  volumes:
      - ./:/opt/apim-cli/data
  args:
      - ${{ inputs.command }}

