# action.yaml
name: "Axway APIM-CLI Github Action"
description: "Use the Axway APIM-CLI in you GitHub action workflows."
inputs:
  apimCLIArgs:
    description: "All arguments required by the APIM-CLI to run. For example 'api import -host manager.hostname.com -port 443 -u apiadmin -p mypassword'"
    required: true
    default: 1
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.apimCLIArgs}}
