# action.yaml
name: "Axway APIM-CLI Github Action"
description: "Use the Axway APIM-CLI in you GitHub action workflows. Import APIs, users, organizations and applications in batch mode."
branding:
  icon: 'award'  
  color: 'red'
  
inputs:
  apimHostname:
    description: "The API-Manager hostname without port or protocol."
    required: true
  apimPort:
    description: "The API-Manager port."
    required: true
    default: "8075"
  apimUsername:
    description: "The API-Manager username."
    required: true
  apimPassword:
    description: "The API-Manager password."
    required: true
  apimExtraArgs:
    description: "Some extra parameters which should be used by the APIM-CLI. For instance '-port 443', '-force' or '-returnCodeMapping 10:0'"
    required: false
  apiDirectory:
    description: "The directory containing your APIs. Each API in a separate directory."
    required: false
  orgDirectory:
    description: "The directory containing your organizations. Each organization in a separate directory."
    required: false
  appDirectory:
    description: "The directory containing your applications. Each application in a separate directory."
    required: false
  userDirectory:
    description: "The directory containing your users. Each user in a separate directory."
    required: false
  apimCLICommand:
    description: "Run an APIM-CLI command. For example: 'apim api check-certs'. You may combine this with apimExtraArgs depending on you the command you use."
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.apimHostname}}
    - ${{ inputs.apimUsername}}
    - ${{ inputs.apimPassword}}
